In [1]:
import numpy as np

In [27]:
# ndarray 객체 z의 원소들로부터 정수 부분만 추출
np.random.seed(0)
z = np.random.uniform(0, 10,10)
print(z)

[5.48813504 7.15189366 6.02763376 5.44883183 4.23654799 6.45894113
 4.37587211 8.91773001 9.63662761 3.83441519]


In [29]:
z = z.astype(int)
z

array([5, 7, 6, 5, 4, 6, 4, 8, 9, 3])

In [51]:
# 행의 값이 0~4 정수 데이터로 구성된 5X5 2차원 배열 객체 생성
index = np.random.randint(5, size=(5,5))
print(index)

[[4 1 4 1 3]
 [2 3 0 1 0]
 [3 1 4 2 3]
 [3 2 3 1 1]
 [3 1 3 3 4]]


In [23]:
# random()함수로 10개의 원소를 생성, 생성된 원소중 최대값을 0으로 변경.
a = np.random.rand(10)
print(a)
a[a == np.max(a)] = int(0)
print(a)

[0.79172504 0.52889492 0.56804456 0.92559664 0.07103606 0.0871293
 0.0202184  0.83261985 0.77815675 0.87001215]
[0.79172504 0.52889492 0.56804456 0.         0.07103606 0.0871293
 0.0202184  0.83261985 0.77815675 0.87001215]


In [25]:
# 크기가 10인 랜덤 벡터를 생성하고 벡터의 원소를 오름차순으로 정렬.
b = np.random.rand(10)
b = np.sort(b)
b

array([0.0187898 , 0.26455561, 0.45615033, 0.56843395, 0.61209572,
       0.616934  , 0.6176355 , 0.6818203 , 0.77423369, 0.94374808])

In [35]:
# z배열 객체에서 빈도수가 가장 높은 값을 찾아 출력
print(z)
val,cnt = np.unique(z, return_counts=True)
idx = np.argmax(cnt)
print(val)
print(cnt)
print(val[idx])

[5 7 6 5 4 6 4 8 9 3]
[3 4 5 6 7 8 9]
[1 2 2 2 1 1 1]
4


In [38]:
# 주사위 100번 던져서 나오는 숫자의 평균을 구하시오.
dice = np.random.randint(1,7, size=100)
print(dice)
np.mean(dice)

[4 3 5 4 6 6 4 1 4 1 5 3 4 6 6 5 1 3 4 4 2 6 4 5 6 6 4 4 2 2 2 4 3 3 5 4 2
 3 4 6 6 6 2 5 3 3 1 2 6 1 5 1 4 3 6 6 1 1 6 2 2 1 4 1 4 1 5 5 1 2 4 5 4 3
 6 2 2 3 2 6 5 6 3 6 6 5 5 6 6 3 4 6 4 2 3 5 4 4 2 2]


3.76

In [37]:
# 가격이 10000원인 주식이 있고, 이 주식의 일간 수익률은 평균이 0, 표준편차가 1인 정규분포를 따른다고 가정할때, 250일 동안의 주가를 무작위로 생성.

[4 3 4 3 2 3 4 4 4 3 4 5 2 3 4 2 3 2 5 3 4 1 4 3 4 1 1 1 4 3 4 1 5 1 6 1 6
 3 4 3 4 6 1 1 1 4 1 3 3 1 5 4 5 6 1 5 4 6 4 5 6 2 6 4 1 1 1 6 6 2 1 5 2 6
 6 4 2 1 1 5 4 4 2 6 6 1 1 2 3 1 4 6 2 2 5 1 6 1 4 3]


3.29

In [48]:
diff_x = np.random.normal(0,1,250)
stock_l = [10000]
dif_s = 10000
for x in diff_x:
    dif_s = dif_s + (x*100)
    stock_l.append(dif_s)
print(len(stock_l))

251


In [49]:
stock_l

[10000,
 9987.95933613356,
 9840.027738137234,
 9806.817510402352,
 9734.674380845177,
 9689.797679534628,
 9515.378903879233,
 9681.439659868684,
 9539.77931162612,
 9259.559031786948,
 9140.716589628646,
 9080.332634349032,
 8965.37722802332,
 9075.207582096571,
 9061.423664236961,
 9063.962224677607,
 9125.001401108148,
 9153.60265380596,
 9251.459383550564,
 9140.511628186949,
 9085.759818119006,
 9152.35653272596,
 8898.901086517537,
 8761.382638585812,
 8811.481861803806,
 8763.456958304314,
 8857.067713315284,
 8937.9857430006,
 8818.176454981496,
 8858.842163728184,
 8979.011949294934,
 8993.755389460031,
 8896.008901735444,
 8983.947895926782,
 9047.490348582181,
 9101.751426932062,
 9173.345316275761,
 8873.884030252999,
 8961.977786361096,
 9142.790967418994,
 9186.454814881923,
 9205.727714531895,
 9275.371581871039,
 9309.19412923955,
 9374.372255409611,
 9374.519355434153,
 9297.848869980464,
 9197.416598759002,
 9097.597425935815,
 8960.293170840725,
 8853.518969738814,


In [50]:
Z = np.zeros((5, 5))
Z += np.arange(5)
print(Z)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [3]:
import pandas as pd
import numpy as np


In [2]:
df1 = pd.DataFrame({ '이름': ['영희', '철수', '철수'], '성적': [1, 2, 3]} )
print(df1)
df2 = pd.DataFrame({ '성명': ['영희', '영희', '철수'], '성적2': [4, 5, 6]} )
print(df2)
print(pd.merge(df1, df2, left_on='이름', right_on="성명"))

   이름  성적
0  영희   1
1  철수   2
2  철수   3
   성명  성적2
0  영희    4
1  영희    5
2  철수    6
   이름  성적  성명  성적2
0  영희   1  영희    4
1  영희   1  영희    5
2  철수   2  철수    6
3  철수   3  철수    6


In [4]:
df1 = pd.DataFrame({ '도시': ['서울', '서울', '서울', '부산', '부산'],
'연도': [2000, 2005, 2010, 2000, 2005],
'인구': [9853972, 9762546, 9631482, 3655437, 3512547]})
print(df1)
df2 = pd.DataFrame( np.arange(12).reshape((6, 2)),
index=[['부산', '부산', '서울', '서울', '서울', '서울'],
[2000, 2005, 2000, 2005, 2010, 2015]],
columns=['데이터1', '데이터2'])
print(df2)

   도시    연도       인구
0  서울  2000  9853972
1  서울  2005  9762546
2  서울  2010  9631482
3  부산  2000  3655437
4  부산  2005  3512547
         데이터1  데이터2
부산 2000     0     1
   2005     2     3
서울 2000     4     5
   2005     6     7
   2010     8     9
   2015    10    11


In [5]:
print(pd.merge(df1, df2, left_on=['도시', '연도'], right_index=True))

   도시    연도       인구  데이터1  데이터2
0  서울  2000  9853972     4     5
1  서울  2005  9762546     6     7
2  서울  2010  9631482     8     9
3  부산  2000  3655437     0     1
4  부산  2005  3512547     2     3
